# Generated by Django 4.0.4 on 2022-05-16 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pesel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Wybory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('poczatekWyborow', models.DateTimeField()),
                ('koniecWyborow', models.DateTimeField()),
                ('maxKandydatow', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OsobaWybory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czyOddalGlos', models.BooleanField(default=False)),
                ('czyKandydat', models.BooleanField(default=False)),
                ('OsobaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wybory.osoba')),
                ('wyboryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wybory.wybory')),
            ],
        ),
        migrations.CreateModel(
            name='Glos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kandydatOsobaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wybory.osoba')),
                ('wyboryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wybory.wybory')),
            ],
        ),
    ]
