# Generated by Django 4.0.4 on 2022-05-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wybory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='pesel',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
