# Generated by Django 4.0.4 on 2022-06-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wybory', '0002_alter_osoba_pesel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wybory',
            name='maxKandydatow',
        ),
        migrations.AddField(
            model_name='wybory',
            name='maxWybranychKandydatow',
            field=models.IntegerField(default=1),
        ),
    ]
