# Generated by Django 4.0.4 on 2022-06-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wybory', '0003_remove_wybory_maxkandydatow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glos',
            old_name='kandydatOsobaID',
            new_name='kandydatOsobaId',
        ),
        migrations.RenameField(
            model_name='osobawybory',
            old_name='OsobaId',
            new_name='osobaId',
        ),
    ]
